name: 'Issue Manager'
description: 'Close issues using special keywords after a period of time with a custom message'
inputs:
  token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  input_settings:
    description: 'JSON with settings as described in the README'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
