name: Issue Manager

on:
  schedule:
  - cron: "* * * * *"
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
    - uses: tiangolo/issue-manager@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

        config: >
          {
            "answered":{
                "delay": 300,
                "users": ["mariacamilagl"],
                "message": "This issue shall be closed."
            }
          }
