on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
    - uses: tiangolo/issue-manager@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config: >
          {
            "$schema": "./schema.json",
            "answered":{
                "delay": 10,
                "users": ["mariacamilagl"],
                "message": "This issue shall be closed."
            }
          }


